## Background

## Artificial Intelligence
Artificial Intelligence is when a machine does something that looks like a person is doing it. This can be something like a set of rules or a complicated system.
For example a program that sends you an email to remind you of something when the due date has passed. We call this Artificial Intelligence because it seems smart.

## Machine Learning
Machine Learning is when a system learns from the information it has and finds patterns. It does not just follow rules that are set in advance. For instance a model that looks at invoices and learns which ones are paid late then it can predict which ones will be paid late in the future.

## Deep Learning
Deep Learning is a type of Machine Learning that uses layers to learn. It can work directly with things like pictures, sound and text. For example a special kind of program called a CNN can look at pictures. Decide if there is a cat in them. It can figure out the edges, shapes and other things about the picture, on its own.

## Data Science
Data Science is the process of working with information. This includes collecting the information making sure it is correct looking at it making pictures of it and using Machine Learning and Deep Learning to answer questions and make decisions. For example looking at sales information making sure it is correct making a graph of the trends building a model to predict what people will buy and then telling everyone what you found out.

In [34]:
# importing libraries
import pandas as pd

Task 1: Logistic Regression with a Single Feature

1) Data retrieval and collection

In [35]:
#load the heart disease dataset
df=pd.read_csv("Heart_Disease_Prediction.csv")
df.head() #checking if data was loaded

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence

In [36]:
#shape of dataset
print("Shape of dataset:",df.shape) #Provides number of rows X columns

#column names
print("Columns:\n", df.columns.tolist())

Shape of dataset: (270, 14)
Columns:
 ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium', 'Heart Disease']

In [37]:
#description of dataset
df.describe()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
count,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.00000,270.000000,270.000000,270.000000
mean,54.433333,0.677778,3.174074,131.344444,249.659259,0.148148,1.022222,149.677778,0.329630,1.05000,1.585185,0.670370,4.696296
std,9.109067,0.468195,0.950090,17.861608,51.686237,0.355906,0.997891,23.165717,0.470952,1.14521,0.614390,0.943896,1.940659
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.00000,1.000000,0.000000,3.000000
25%,48.000000,0.000000,3.000000,120.000000,213.000000,0.000000,0.000000,133.000000,0.000000,0.00000,1.000000,0.000000,3.000000
50%,55.000000,1.000000,3.000000,130.000000,245.000000,0.000000,2.000000,153.500000,0.000000,0.80000,2.000000,0.000000,3.000000
75%,61.000000,1.000000,4.000000,140.000000,280.000000,0.000000,2.000000,166.000000,1.000000,1.60000,2.000000,1.000000,7.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.20000,3.000000,3.000000,7.000000

 ## 2) Data cleaning

 As the real world data usually contains missing values, duplicate records, invalid entries and incorrect data types, therefore we need to clean those data inorder to improve model performance.

In [38]:
# check missing values
print(df.isnull().sum())

Age                        0
Sex                        0
Chest pain type            0
BP                         0
Cholesterol                0
FBS over 120               0
EKG results                0
Max HR                     0
Exercise angina            0
ST depression              0
Slope of ST                0
Number of vessels fluro    0
Thallium                   0
Heart Disease              0
dtype: int64

no missing values for any columns

In [39]:
df['Cholesterol'].describe()

count    270.000000
mean     249.659259
std       51.686237
min      126.000000
25%      213.000000
50%      245.000000
75%      280.000000
max      564.000000
Name: Cholesterol, dtype: float64

Having cholestrol 0 or less than 0 is medically invalid. So checking if there is any and if present remove that line.

In [40]:

# Checking if there is any invalid entries in the cholesterol column

print((df["Cholesterol"]<=0).sum())
df= df[df["Cholesterol"]>0]

0

Verifying the target values and checking the data type of it.

In [41]:
# Provides the data type as well as the unique data value in the column
print(df["Heart Disease"].unique())

<StringArray>
['Presence', 'Absence']
Length: 2, dtype: str

For logistic regression, we need numeric labels rather tah string array. So converting target into binary i.e. 0 and 1 using the 'map' function where "Absence" => 0 and "Presence" => 1

In [42]:
df["Heart Disease"] = df["Heart Disease"].map({
    "Absence": 0,
    "Presence": 1
})

The target in now encoded to 0 and 1

In [43]:
print(df["Heart Disease"].unique())

[1 0]

## 3) Feature Design

Feature Design determines which variables are used as model inputs.

For Task 1: 
      
      Input Variable => Cholesterol
      Output => Heart Disease

In [66]:
X = df[["Cholesterol"]]  #input variable
Y = df["Heart Disease"] #target (Output variable)

Cholesterol consists of "[[]]" so that it represents 2D. It is converted into DataFrame(2D) because even if there is only one feature, Scikit-Learn still expects (270,1) rather than (270,) which represents series. 
Instead of using "double []" we can convert X into dataframe too using syntax => X.to_frame().

ML models need the DataFrame format (270,1) => Samples X Features because they are designed to handle multiple features.

In [67]:
print(type(X))
print(X.shape)
print(type(Y))
print(Y.shape)

<class 'pandas.DataFrame'>
(270, 1)
<class 'pandas.Series'>
(270,)

In [68]:
print(X) #consists of cholesterol data (predictor)
print(Y) #consists of heart disease data (target)

     Cholesterol
0            322
1            564
2            261
3            263
4            269
..           ...
265          199
266          263
267          294
268          192
269          286

[270 rows x 1 columns]
0      1
1      0
2      1
3      0
4      0
      ..
265    0
266    0
267    0
268    0
269    1
Name: Heart Disease, Length: 270, dtype: int64

We took cholesterol as the only input feature for target heart disease as it is medically relevant because high cholesterol leads to artery blockage and cardiovascular disease. (Logistic Regression with a Single Feature)

## 4) Algorithm Selection

Using logistic regression as algorithm because

In [69]:
# importing logistic regression

from sklearn.linear_model import LogisticRegression

Creating a model 
Creates an empty Logistic Regression model

In [70]:
model_single = LogisticRegression() #No training occurs yet

## 5) Loss Function Selection

To see how good or bad the models guess is we use something called Binary Cross-Entropy or Log Loss for short.
The formula for this is:
L=−[ylog(y')+(1−y)log(1−y')]

This formula helps us understand how off the models guess is from the real answer. If the model gets it wrong it gets penalized.. If it gets it right it gets a reward. The model is trying to adjust its settings to make the loss as small as possible. The problem with using one feature, like cholesterol level is that the model cannot understand really complicated relationships. This means it might not be very good at guessing and the loss value might be higher. As a result the models predictions might not be very accurate. Logistic regression, with one feature is limited so it might not give us the results.

## 6) Model Learning(Training)

Importing Train-Test Split

In [71]:
from sklearn.model_selection import train_test_split

Split data so that it consists : train = 80% and test= 20%
This is done so that the model can provide generalized data rather than fixated answer which is obtained after training and testing in the same dataset. So inorder to avoid that we separate 20% of data to test the model which is trained from the remaining 80% of data.

In [72]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2, 
    random_state= 42 #Ensures reproducible results
)

Train Model:
    The model learns coefficient, intercept by minimizing log-loss.

In [73]:
print(X_train.dtypes)
print(Y_train.dtype)
print(type(model_single))

Cholesterol    int64
dtype: object
int64
<class 'sklearn.linear_model._logistic.LogisticRegression'>

In [74]:
model_single.fit(X_train, Y_train)

LogisticRegression()

model_single.fit(X_train, y_train) teaches the Logistic Regression model to learn the relationship between cholesterol and heart disease by finding the best coefficient and intercept that minimize prediction error on the training data.

Displaying parameters

Coefficient:

Shows the influence of cholesterol

Positive coefficient => Higher cholesterol -> Higher heart disease probability
Negative coefficient => Higher cholesterol -> Lower heart disease probability

In [75]:
print(model_single.coef_)

print(model_single.intercept_)

[[0.00351491]]
[-1.04698442]

## 7) Model Evaluation

In [76]:
#importing metrics
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

Prediciting Test data

In [77]:
Y_pred = model_single.predict(X_test)

Accuracy:
Measures overall correctness

In [78]:
accuracy = accuracy_score(Y_test, Y_pred)

print(accuracy)

0.6111111111111112

Precision: Measures how many predicted heart disease cases are actually heart disease

In [79]:
precision = precision_score(Y_test, Y_pred)

print(precision)

0.5

Recall : Measures how many actual heart disease patients were detected.

Important in healthcare because missing a sick patient is dangerous.

In [80]:
recall = recall_score(Y_test, Y_pred)

print(recall)

0.23809523809523808

F1 Score= Balances precision and recall.

In [81]:
f1 = f1_score(Y_test, Y_pred)

print(f1)

0.3225806451612903

Confustion matrix shows:
|            | Predicted No | Predicted Yes |
| ---------- | ------------ | ------------- |
| Actual No  | TN           | FP            |
| Actual Yes | FN           | TP            |

In [82]:
cm = confusion_matrix(Y_test, Y_pred)

print(cm)

[[28  5]
 [16  5]]

Classification Report: 
Provides:

Precision
Recall
F1-score
Support

for each class.

In [83]:
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.64      0.85      0.73        33
           1       0.50      0.24      0.32        21

    accuracy                           0.61        54
   macro avg       0.57      0.54      0.52        54
weighted avg       0.58      0.61      0.57        54

# Task 2

Unlike Task 1, where only Cholesterol was used, here we use all available features. This allows the model to learn relationships from multiple risk factors such as Age, Blood Pressure, Maximum Heart Rate, and ST Depression.

# 3) Feature Design

Creating features and labels

In [44]:
x = df.drop("Heart Disease", axis=1)

y = df["Heart Disease"]

In [8]:
print(x.shape)
print(y.shape)

(270, 13)
(270,)

The above output means 270 patients and 13 input features.

### Feature Scaling

Since we have multiple input features so any large value in any of the features will be dominant in the model which will affect it. So inorder to have them in generalized form we scale them in common range.

In [45]:
#import standard scaler
from sklearn.preprocessing import StandardScaler

Standard Scaler transforms each feature where mean will be 0 and distribution will be 1. z= (x−μ)/σ​

In [46]:
scaler = StandardScaler()

x_scaled = scaler.fit_transform(x)

# 4) Algorithm Selection

Importing logistic regression

In [50]:
from sklearn.linear_model import LogisticRegression

Creating model with multiple iterations so that it gives the optimization algorithm enough iterations to converge

In [51]:
model_multi = LogisticRegression(max_iter=1000)

## 5) Loss Function Selection

Logistic Regression uses Binary Cross-Entropy, also known as Log Loss, to measure prediction error. This loss function evaluates how closely the predicted probabilities match the actual class labels. Incorrect predictions with high confidence receive a larger penalty, encouraging the model to produce more accurate probability estimates.

L=−[ylog(y')+(1−y)log(1−y')]

## 6) Model learning(training)

Same as task 1

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
x_train, x_test, y_train, y_test = train_test_split(
    x_scaled,
    y,
    test_size=0.2,
    random_state=42
)

Train model

In [54]:
model_multi.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

The model learns 13 coefficient (1 for each feature) and 1 intercept

In [55]:
# Display intercept
print("Intercept:")
print(model_multi.intercept_)

Intercept:
[-0.32406426]

In [56]:
#Display coefficients
coef_df = pd.DataFrame({
    "Feature": x.columns,
    "Coefficient": model_multi.coef_[0]
})

coef_df.sort_values(
    by="Coefficient",
    ascending=False
)

                    Feature  Coefficient
11  Number of vessels fluro     0.825942
1                       Sex     0.641974
2           Chest pain type     0.622302
12                 Thallium     0.568689
9             ST depression     0.503783
3                        BP     0.432721
8           Exercise angina     0.377017
10              Slope of ST     0.336905
4               Cholesterol     0.286744
6               EKG results     0.067388
0                       Age    -0.083107
7                    Max HR    -0.213840
5              FBS over 120    -0.335244

Here +ve coefficient => Feature increases heart disease risk
-ve coefficient => Feature decreases heart disease risk

## Model Evaluation

In [57]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [58]:
#Make predictions
y_pred_multi = model_multi.predict(x_test)

In [59]:
#Accuracy
accuracy_multi = accuracy_score(
    y_test,
    y_pred_multi
)

print("Accuracy:", accuracy_multi)

Accuracy: 0.9074074074074074

In [60]:
#Precision 
precision_multi = precision_score(
    y_test,
    y_pred_multi
)

print("Precision:", precision_multi)

Precision: 0.9

In [61]:
#Recall
recall_multi = recall_score(
    y_test,
    y_pred_multi
)

print("Recall:", recall_multi)

Recall: 0.8571428571428571

In [62]:
#F1 Score
f1_multi = f1_score(
    y_test,
    y_pred_multi
)

print("F1 Score:", f1_multi)

F1 Score: 0.8780487804878049

In [63]:
#Confusion Matrix
cm_multi = confusion_matrix(
    y_test,
    y_pred_multi
)

print(cm_multi)

[[31  2]
 [ 3 18]]

In [64]:
#Classification Report

print(
    classification_report(
        y_test,
        y_pred_multi
    )
)

              precision    recall  f1-score   support

           0       0.91      0.94      0.93        33
           1       0.90      0.86      0.88        21

    accuracy                           0.91        54
   macro avg       0.91      0.90      0.90        54
weighted avg       0.91      0.91      0.91        54

## Model Comparison

In [84]:
comparison = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],
    "Task 1 (Cholesterol Only)": [
        accuracy,
        precision,
        recall,
        f1
    ],
    "Task 2 (All Features)": [
        accuracy_multi,
        precision_multi,
        recall_multi,
        f1_multi
    ]
})

comparison

      Metric  Task 1 (Cholesterol Only)  Task 2 (All Features)
0   Accuracy                   0.611111               0.907407
1  Precision                   0.500000               0.900000
2     Recall                   0.238095               0.857143
3   F1 Score                   0.322581               0.878049

The Logistic Regression model that uses more features works better than the one that only uses one feature. This is because it looks at things that are related to health not just cholesterol levels. Heart disease is affected by a lot of things like how old you're your blood pressure, what kind of chest pain you have your heart rate and the results of your ECG. So when you use information that is relevant you can make better predictions.

When you add things to look at the model usually gets better at making predictions and finding the people who really have heart disease. This is especially important in healthcare because it helps find people who actually have heart disease so you do not miss as many cases.

The Logistic Regression model that uses many features is good but it is harder to understand. This is because many things are used to make a prediction, not one or two things. On the other hand the model that only uses one feature is easier to understand because it only looks at cholesterol levels.

In the end the model that uses many features is better for making predictions about heart disease. However the model that only uses one feature is useful for seeing how cholesterol affects the risk of getting heart disease. The Logistic Regression model that uses many features is preferred because it can make better predictions and that is important, for helping people with heart disease.

## Discussion

In this assignment, we compared two Logistic Regression models to predict heart disease. One model used the Cholesterol feature. The other model used all the features.The results showed that the model with all the features did a good job. This is because it used information about a patients health. It looked at things like age, blood pressure, chest pain type and heart rate.The model with all the features was better at finding patterns that are associated with heart disease. So it was more accurate. It was also better at predicting heart disease. On the other hand the model that only used Cholesterol was easier to understand. This is because it only looked at cholesterol levels to make predictions. This shows that there is a trade off. If you want a model that's easy to understand it might not be as good at predicting heart disease. If you use a model with multiple features like heart disease prediction models it will be more effective. The experiment showed that using relevant features makes a big difference in predicting heart disease. Heart disease prediction is easier, with features.

## Conclusion

This assignment showed that the entire Machine Learning process works well for classifying heart disease using Logistic Regression. The process had steps: collecting, data cleaning, designing features, training the model and evaluating its performance. We made two models: one that used Cholesterol and another that used all the available information. The results of the evaluation showed that the model with features was better at predicting because it knew more about the patients heart health. We looked at things like how accurate it was how precise it was, how well it remembered things and its F1-score and all of these things showed that using features was better. This study also showed how important it is to pick the features and get the data ready when building a machine learning model. In the end Logistic Regression was an algorithm for classifying things into two groups and using many relevant medical features made it better, at predicting heart disease. The Machine Learning pipeline and Logistic Regression and the heart disease classification all worked well together. The heart disease classification was more accurate when we used features and Logistic Regression.